/// <reference types="@webgpu/types" />

import { mat4, vec4 } from 'gl-matrix';
import type { Format, Layout } from '../types';
import { VideoFrameTracker } from './renderer';

const WGSL = `
struct Uniforms {
  inverseModelViewProjection: mat4x4<f32>,
  modelSpaceEye: vec3<f32>,
  _padding0: f32,
  texCoordScaleOffset: vec4<f32>,
};

@group(0) @binding(0)
var<uniform> uniforms: Uniforms;

@group(0) @binding(1)
var videoTexture: texture_external;

@group(0) @binding(2)
var videoSampler: sampler;

struct VertexOutput {
  @builtin(position) position: vec4<f32>,
  @location(0) clipCoord: vec2<f32>,
};

@vertex
fn vertexMain(
  @builtin(vertex_index) index: u32,
) -> VertexOutput {
  var positions = array<vec2<f32>, 6>(
    vec2<f32>(-1.0, -1.0),
    vec2<f32>(1.0, -1.0),
    vec2<f32>(1.0, 1.0),

    vec2<f32>(-1.0, -1.0),
    vec2<f32>(1.0, 1.0),
    vec2<f32>(-1.0, 1.0),
  );

  var output: VertexOutput;

  output.position = vec4<f32>(
    positions[index],
    0.0,
    1.0
  );

  output.clipCoord = positions[index];

  return output;
}

fn getRay(
  clipCoord: vec2<f32>,
) -> vec3<f32> {
  /*
   * WebGPU uses a depth range of 0..1.
   *
   * The near point therefore uses Z = 0
   * and the far point uses Z = 1.
   */
  let nearModel =
    uniforms.inverseModelViewProjection *
    vec4<f32>(
      clipCoord,
      0.0,
      1.0
    );

  let farModel =
    uniforms.inverseModelViewProjection *
    vec4<f32>(
      clipCoord,
      1.0,
      1.0
    );

  let nearPoint =
    nearModel.xyz / nearModel.w;

  let farPoint =
    farModel.xyz / farModel.w;

  return normalize(
    farPoint - nearPoint
  );
}

fn sphereUV(
  hit: vec3<f32>,
) -> vec2<f32> {
  let theta =
    atan2(hit.z, hit.x);

  let phi =
    asin(clamp(hit.y, -1.0, 1.0));

  return vec2<f32>(
    theta / 6.28318530718 + 0.5,
    0.5 - phi / 3.14159265359
  );
}

@fragment
fn fragmentMain(
  input: VertexOutput,
) -> @location(0) vec4<f32> {
  let origin =
    uniforms.modelSpaceEye;

  let direction =
    getRay(
      input.clipCoord,
    );

  let halfB =
    dot(origin, direction);

  let c =
    dot(origin, origin) - 1.0;

  let discriminant =
    halfB * halfB - c;

  if (discriminant < 0.0) {
    discard;
  }

  let t =
    -halfB + sqrt(discriminant);

  let hit =
    origin + t * direction;

  var uv =
    sphereUV(hit);

  /*
   * 180 degree video.
   */
  if (FORMAT == 1) {
    if (
      uv.x < 0.25 ||
      uv.x > 0.75
    ) {
      discard;
    }

    uv.x =
      (uv.x - 0.25) * 2.0;
  }

  /*
   * Flat screen video.
   */
  if (FORMAT == 2) {
    if (abs(direction.z) < 0.00001) {
      discard;
    }

    let planeT =
      -origin.z / direction.z;

    if (planeT < 0.0) {
      discard;
    }

    let planeHit =
      origin + planeT * direction;

    if (
      abs(planeHit.x) > 1.0 ||
      abs(planeHit.y) > 1.0
    ) {
      discard;
    }

    uv =
      vec2<f32>(
        1.0 -
          (planeHit.x * 0.5 + 0.5),
        planeHit.y * 0.5 + 0.5
      );
  }

  /*
   * Do not flip Y here.
   *
   * WebGPU's external video texture already has
   * browser/video coordinate handling applied.
   */
  let mappedUV =
    uv *
      uniforms.texCoordScaleOffset.xy +
    uniforms.texCoordScaleOffset.zw;

  return textureSampleBaseClampToEdge(
    videoTexture,
    videoSampler,
    mappedUV
  );
}
`;

function formatDefine(
  format: Format,
): string {
  switch (format) {
    case '360':
      return 'const FORMAT: i32 = 0;';

    case '180':
      return 'const FORMAT: i32 = 1;';

    case 'screen':
    default:
      return 'const FORMAT: i32 = 2;';
  }
}

/*
 * WebGPU perspective projection.
 *
 * Unlike the normal OpenGL projection generated by
 * mat4.perspective(), this uses the WebGPU depth range:
 *
 *     Z = 0 ... 1
 */
function perspectiveWebGPU(
  out: mat4,
  fovy: number,
  aspect: number,
  near: number,
  far: number,
): mat4 {
  const f =
    1 / Math.tan(fovy / 2);

  out[0] = f / aspect;
  out[1] = 0;
  out[2] = 0;
  out[3] = 0;

  out[4] = 0;
  out[5] = f;
  out[6] = 0;
  out[7] = 0;

  out[8] = 0;
  out[9] = 0;
  out[10] =
    far / (near - far);
  out[11] = -1;

  out[12] = 0;
  out[13] = 0;
  out[14] =
    (near * far) /
    (near - far);
  out[15] = 0;

  return out;
}

export class WebGPUDebugRenderer {
  private raf = 0;

  private frameTracker:
    | VideoFrameTracker
    | null = null;

  private device!: GPUDevice;
  private context!: GPUCanvasContext;
  private pipeline!: GPURenderPipeline;
  private uniformBuffer!: GPUBuffer;
  private sampler!: GPUSampler;

  private yaw = 0;
  private pitch = 0;
  private fov = Math.PI / 2;

  private dragging = false;
  private lastX = 0;
  private lastY = 0;

  private bindGroup!: GPUBindGroup;

  constructor(
    private readonly video: HTMLVideoElement,
    private readonly canvas: HTMLCanvasElement,
    private readonly layout: Layout,
    private readonly flipLayout: boolean,
    private readonly format: Format,
    private readonly eye: 'left' | 'right',
  ) {
    this.canvas.style.cursor = 'grab';

    this.canvas.addEventListener(
      'pointerdown',
      this.handlePointerDown,
    );

    this.canvas.addEventListener(
      'pointermove',
      this.handlePointerMove,
    );

    this.canvas.addEventListener(
      'pointerup',
      this.handlePointerUp,
    );

    this.canvas.addEventListener(
      'pointercancel',
      this.handlePointerUp,
    );

    this.canvas.addEventListener(
      'wheel',
      this.handleWheel,
      { passive: false },
    );

    window.addEventListener(
      'keydown',
      this.handleKeyDown,
    );

    window.addEventListener(
      'resize',
      this.handleWindowResize,
    );
  }

  private handlePointerDown = (
    event: PointerEvent,
  ) => {
    if (event.button !== 0) {
      return;
    }

    this.dragging = true;

    this.lastX = event.clientX;
    this.lastY = event.clientY;

    this.canvas.style.cursor =
      'grabbing';

    this.canvas.setPointerCapture(
      event.pointerId,
    );
  };

  private handlePointerMove = (
    event: PointerEvent,
  ) => {
    if (!this.dragging) {
      return;
    }

    const dx =
      event.clientX - this.lastX;

    const dy =
      event.clientY - this.lastY;

    this.lastX = event.clientX;
    this.lastY = event.clientY;

    this.yaw += dx * 0.005;
    this.pitch += dy * 0.005;

    const limit =
      Math.PI / 2 - 0.01;

    this.pitch = Math.max(
      -limit,
      Math.min(limit, this.pitch),
    );
  };

  private handlePointerUp = (
    event: PointerEvent,
  ) => {
    this.dragging = false;

    this.canvas.style.cursor =
      'grab';

    if (
      this.canvas.hasPointerCapture(
        event.pointerId,
      )
    ) {
      this.canvas.releasePointerCapture(
        event.pointerId,
      );
    }
  };

  private handleWheel = (
    event: WheelEvent,
  ) => {
    event.preventDefault();

    this.fov +=
      event.deltaY * 0.0015;

    this.fov = Math.max(
      Math.PI / 6,
      Math.min(
        Math.PI * 0.85,
        this.fov,
      ),
    );
  };

  private handleKeyDown = (
    event: KeyboardEvent,
  ) => {
    if (
      event.key.toLowerCase() === 'r'
    ) {
      this.yaw = 0;
      this.pitch = 0;
      this.fov = Math.PI / 2;
    }
  };

  private handleWindowResize = () => {
    this.resizeCanvas();
  };

  private resizeCanvas() {
    const dpr = Math.min(
      window.devicePixelRatio || 1,
      2,
    );

    const width = Math.max(
      1,
      Math.round(
        this.canvas.clientWidth * dpr,
      ),
    );

    const height = Math.max(
      1,
      Math.round(
        this.canvas.clientHeight * dpr,
      ),
    );

    if (
      this.canvas.width !== width ||
      this.canvas.height !== height
    ) {
      this.canvas.width = width;
      this.canvas.height = height;
    }
  }

  async start(): Promise<void> {
    const gpu = navigator.gpu;

    if (!gpu) {
      throw new Error(
        'WebGPU is not supported by this browser.',
      );
    }

    const adapter =
      await gpu.requestAdapter();

    if (!adapter) {
      throw new Error(
        'Unable to acquire a WebGPU adapter.',
      );
    }

    this.device =
      await adapter.requestDevice();

    const context =
      this.canvas.getContext('webgpu');

    if (!context) {
      throw new Error(
        'Unable to create WebGPU canvas context.',
      );
    }

    this.context = context;

    const canvasFormat =
      gpu.getPreferredCanvasFormat();

    this.resizeCanvas();

    this.context.configure({
      device: this.device,
      format: canvasFormat,
      alphaMode: 'opaque',
    });

    const shaderCode =
      `${formatDefine(this.format)}\n${WGSL}`;

    const shaderModule =
      this.device.createShaderModule({
        code: shaderCode,
      });

    this.uniformBuffer =
      this.device.createBuffer({
        size: 128,
        usage:
          GPUBufferUsage.UNIFORM |
          GPUBufferUsage.COPY_DST,
      });

    this.sampler =
      this.device.createSampler({
        magFilter: 'linear',
        minFilter: 'linear',
        addressModeU: 'clamp-to-edge',
        addressModeV: 'clamp-to-edge',
      });

    this.pipeline =
      this.device.createRenderPipeline({
        layout: 'auto',

        vertex: {
          module: shaderModule,
          entryPoint: 'vertexMain',
        },

        fragment: {
          module: shaderModule,
          entryPoint: 'fragmentMain',

          targets: [
            {
              format: canvasFormat,
            },
          ],
        },

        primitive: {
          topology: 'triangle-list',
        },
      });

    this.frameTracker =
      new VideoFrameTracker(
        this.video,
      );

    this.render();
  }

  private render = () => {
    this.resizeCanvas();

    if (
      this.canvas.width <= 0 ||
      this.canvas.height <= 0
    ) {
      this.raf =
        requestAnimationFrame(
          this.render,
        );

      return;
    }

    const projection =
      perspectiveWebGPU(
        mat4.create(),
        this.fov,
        this.canvas.width /
          Math.max(
            this.canvas.height,
            1,
          ),
        0.01,
        100,
      );

    const direction =
      vec4.fromValues(
        0,
        0,
        -1,
        0,
      );

    const rotation =
      mat4.create();

    mat4.rotateY(
      rotation,
      rotation,
      this.yaw,
    );

    mat4.rotateX(
      rotation,
      rotation,
      this.pitch,
    );

    vec4.transformMat4(
      direction,
      direction,
      rotation,
    );

    const view =
      mat4.lookAt(
        mat4.create(),
        [0, 0, 0],
        [
          direction[0],
          direction[1],
          direction[2],
        ],
        [0, 1, 0],
      );

    const vp =
      mat4.multiply(
        mat4.create(),
        projection,
        view,
      );

    const inverseVP =
      mat4.create();

    if (
      mat4.invert(
        inverseVP,
        vp,
      ) === null
    ) {
      this.raf =
        requestAnimationFrame(
          this.render,
        );

      return;
    }

    const model =
      this.getModelMatrix();

    const inverseModel =
      mat4.create();

    if (
      mat4.invert(
        inverseModel,
        model,
      ) === null
    ) {
      this.raf =
        requestAnimationFrame(
          this.render,
        );

      return;
    }

    const inverseModelViewProjection =
      mat4.multiply(
        mat4.create(),
        inverseModel,
        inverseVP,
      );

    const modelEye =
      vec4.fromValues(
        0,
        0,
        0,
        1,
      );

    vec4.transformMat4(
      modelEye,
      modelEye,
      inverseModel,
    );

    const offsets =
      this.getTexCoordScaleOffsets();

    const offset =
      this.eye === 'left'
        ? offsets[0]
        : offsets[1];

    const uniformData =
      new Float32Array(32);

    uniformData.set(
      inverseModelViewProjection,
      0,
    );

    uniformData.set(
      [
        modelEye[0],
        modelEye[1],
        modelEye[2],
        0,
      ],
      16,
    );

    uniformData.set(
      offset,
      20,
    );

    this.device.queue.writeBuffer(
      this.uniformBuffer,
      0,
      uniformData,
    );

    /*
     * External video textures must be imported
     * from the current video source for the frame
     * being rendered.
     */
    const texture =
      this.device.importExternalTexture({
        source: this.video,
      });

    this.bindGroup =
      this.device.createBindGroup({
        layout:
          this.pipeline.getBindGroupLayout(
            0,
          ),

        entries: [
          {
            binding: 0,
            resource: {
              buffer:
                this.uniformBuffer,
            },
          },
          {
            binding: 1,
            resource: texture,
          },
          {
            binding: 2,
            resource: this.sampler,
          },
        ],
      });

    const commandEncoder =
      this.device.createCommandEncoder();

    const viewTexture =
      this.context
        .getCurrentTexture()
        .createView();

    const colorAttachments:
      GPURenderPassColorAttachment[] = [
        {
          view: viewTexture,

          clearValue: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },

          loadOp: 'clear',
          storeOp: 'store',
        },
      ];

    const pass =
      commandEncoder.beginRenderPass({
        colorAttachments,
      });

    pass.setPipeline(
      this.pipeline,
    );

    pass.setBindGroup(
      0,
      this.bindGroup,
    );

    pass.draw(6);

    pass.end();

    this.device.queue.submit([
      commandEncoder.finish(),
    ]);

    this.raf =
      requestAnimationFrame(
        this.render,
      );
  };

  private getModelMatrix() {
    const aspectRatio =
      this.getAspectRatio();

    const model =
      mat4.create();

    mat4.rotateY(
      model,
      model,
      Math.PI,
    );

    if (this.format === 'screen') {
      mat4.scale(
        model,
        model,
        [
          aspectRatio,
          1,
          1,
        ],
      );

      mat4.translate(
        model,
        model,
        [0, 0, 1],
      );
    }

    if (this.format !== 'screen') {
      mat4.rotateY(
        model,
        model,
        -Math.PI / 2,
      );
    }

    return model;
  }

  private getAspectRatio() {
    if (
      this.video.videoWidth <= 0 ||
      this.video.videoHeight <= 0
    ) {
      return 1;
    }

    switch (this.layout) {
      case 'stereoLeftRight':
        return (
          this.video.videoWidth * 0.5 /
          this.video.videoHeight
        );

      case 'stereoTopBottom':
        return (
          this.video.videoWidth /
          this.video.videoHeight *
          0.5
        );

      case 'mono':
      default:
        return (
          this.video.videoWidth /
          this.video.videoHeight
        );
    }
  }

  private getTexCoordScaleOffsets() {
    let offsets: Float32Array[];

    switch (this.layout) {
      case 'stereoLeftRight':
        offsets = [
          new Float32Array([
            0.5, 1, 0, 0,
          ]),

          new Float32Array([
            0.5, 1, 0.5, 0,
          ]),
        ];
        break;

      case 'stereoTopBottom':
        offsets = [
          new Float32Array([
            1, 0.5, 0, 0,
          ]),

          new Float32Array([
            1, 0.5, 0, 0.5,
          ]),
        ];
        break;

      default:
        offsets = [
          new Float32Array([
            1, 1, 0, 0,
          ]),

          new Float32Array([
            1, 1, 0, 0,
          ]),
        ];
    }

    return this.flipLayout
      ? offsets.reverse()
      : offsets;
  }

  stop() {
    cancelAnimationFrame(
      this.raf,
    );

    this.frameTracker?.stop();

    this.device?.destroy();

    window.removeEventListener(
      'keydown',
      this.handleKeyDown,
    );

    window.removeEventListener(
      'resize',
      this.handleWindowResize,
    );

    this.canvas.removeEventListener(
      'pointerdown',
      this.handlePointerDown,
    );

    this.canvas.removeEventListener(
      'pointermove',
      this.handlePointerMove,
    );

    this.canvas.removeEventListener(
      'pointerup',
      this.handlePointerUp,
    );

    this.canvas.removeEventListener(
      'pointercancel',
      this.handlePointerUp,
    );

    this.canvas.removeEventListener(
      'wheel',
      this.handleWheel,
    );
  }
}
